//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVP.AdministradorService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdministradorDOM", Namespace="http://schemas.datacontract.org/2004/07/AdministradorService.Dominio")]
    [System.SerializableAttribute()]
    public partial class AdministradorDOM : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CelularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdAdministradorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumDocumentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Celular {
            get {
                return this.CelularField;
            }
            set {
                if ((object.ReferenceEquals(this.CelularField, value) != true)) {
                    this.CelularField = value;
                    this.RaisePropertyChanged("Celular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasenia {
            get {
                return this.ContraseniaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseniaField, value) != true)) {
                    this.ContraseniaField = value;
                    this.RaisePropertyChanged("Contrasenia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAdministrador {
            get {
                return this.IdAdministradorField;
            }
            set {
                if ((this.IdAdministradorField.Equals(value) != true)) {
                    this.IdAdministradorField = value;
                    this.RaisePropertyChanged("IdAdministrador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumDocumento {
            get {
                return this.NumDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumDocumentoField, value) != true)) {
                    this.NumDocumentoField = value;
                    this.RaisePropertyChanged("NumDocumento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/AdministradorService.Errores")]
    [System.SerializableAttribute()]
    public partial class RepetidoException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdministradorService.IAdministrador")]
    public interface IAdministrador {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministrador/Autenticar", ReplyAction="http://tempuri.org/IAdministrador/AutenticarResponse")]
        EVP.AdministradorService.AdministradorDOM Autenticar(string NroDocumento, string Contrasenia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministrador/Autenticar", ReplyAction="http://tempuri.org/IAdministrador/AutenticarResponse")]
        System.Threading.Tasks.Task<EVP.AdministradorService.AdministradorDOM> AutenticarAsync(string NroDocumento, string Contrasenia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministrador/Crear", ReplyAction="http://tempuri.org/IAdministrador/CrearResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EVP.AdministradorService.RepetidoException), Action="http://tempuri.org/IAdministrador/CrearRepetidoExceptionFault", Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/AdministradorService.Errores")]
        EVP.AdministradorService.AdministradorDOM Crear(EVP.AdministradorService.AdministradorDOM Parametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministrador/Crear", ReplyAction="http://tempuri.org/IAdministrador/CrearResponse")]
        System.Threading.Tasks.Task<EVP.AdministradorService.AdministradorDOM> CrearAsync(EVP.AdministradorService.AdministradorDOM Parametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministrador/Obtener", ReplyAction="http://tempuri.org/IAdministrador/ObtenerResponse")]
        EVP.AdministradorService.AdministradorDOM Obtener(string NroDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministrador/Obtener", ReplyAction="http://tempuri.org/IAdministrador/ObtenerResponse")]
        System.Threading.Tasks.Task<EVP.AdministradorService.AdministradorDOM> ObtenerAsync(string NroDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministrador/Modificar", ReplyAction="http://tempuri.org/IAdministrador/ModificarResponse")]
        EVP.AdministradorService.AdministradorDOM Modificar(EVP.AdministradorService.AdministradorDOM Parametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministrador/Modificar", ReplyAction="http://tempuri.org/IAdministrador/ModificarResponse")]
        System.Threading.Tasks.Task<EVP.AdministradorService.AdministradorDOM> ModificarAsync(EVP.AdministradorService.AdministradorDOM Parametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministrador/Eliminar", ReplyAction="http://tempuri.org/IAdministrador/EliminarResponse")]
        string Eliminar(string IdAdministradorDOM);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministrador/Eliminar", ReplyAction="http://tempuri.org/IAdministrador/EliminarResponse")]
        System.Threading.Tasks.Task<string> EliminarAsync(string IdAdministradorDOM);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministrador/Listar", ReplyAction="http://tempuri.org/IAdministrador/ListarResponse")]
        EVP.AdministradorService.AdministradorDOM[] Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministrador/Listar", ReplyAction="http://tempuri.org/IAdministrador/ListarResponse")]
        System.Threading.Tasks.Task<EVP.AdministradorService.AdministradorDOM[]> ListarAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdministradorChannel : EVP.AdministradorService.IAdministrador, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdministradorClient : System.ServiceModel.ClientBase<EVP.AdministradorService.IAdministrador>, EVP.AdministradorService.IAdministrador {
        
        public AdministradorClient() {
        }
        
        public AdministradorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdministradorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdministradorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdministradorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EVP.AdministradorService.AdministradorDOM Autenticar(string NroDocumento, string Contrasenia) {
            return base.Channel.Autenticar(NroDocumento, Contrasenia);
        }
        
        public System.Threading.Tasks.Task<EVP.AdministradorService.AdministradorDOM> AutenticarAsync(string NroDocumento, string Contrasenia) {
            return base.Channel.AutenticarAsync(NroDocumento, Contrasenia);
        }
        
        public EVP.AdministradorService.AdministradorDOM Crear(EVP.AdministradorService.AdministradorDOM Parametro) {
            return base.Channel.Crear(Parametro);
        }
        
        public System.Threading.Tasks.Task<EVP.AdministradorService.AdministradorDOM> CrearAsync(EVP.AdministradorService.AdministradorDOM Parametro) {
            return base.Channel.CrearAsync(Parametro);
        }
        
        public EVP.AdministradorService.AdministradorDOM Obtener(string NroDocumento) {
            return base.Channel.Obtener(NroDocumento);
        }
        
        public System.Threading.Tasks.Task<EVP.AdministradorService.AdministradorDOM> ObtenerAsync(string NroDocumento) {
            return base.Channel.ObtenerAsync(NroDocumento);
        }
        
        public EVP.AdministradorService.AdministradorDOM Modificar(EVP.AdministradorService.AdministradorDOM Parametro) {
            return base.Channel.Modificar(Parametro);
        }
        
        public System.Threading.Tasks.Task<EVP.AdministradorService.AdministradorDOM> ModificarAsync(EVP.AdministradorService.AdministradorDOM Parametro) {
            return base.Channel.ModificarAsync(Parametro);
        }
        
        public string Eliminar(string IdAdministradorDOM) {
            return base.Channel.Eliminar(IdAdministradorDOM);
        }
        
        public System.Threading.Tasks.Task<string> EliminarAsync(string IdAdministradorDOM) {
            return base.Channel.EliminarAsync(IdAdministradorDOM);
        }
        
        public EVP.AdministradorService.AdministradorDOM[] Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<EVP.AdministradorService.AdministradorDOM[]> ListarAsync() {
            return base.Channel.ListarAsync();
        }
    }
}
